[project]
name = "course-backend-api-design"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2",
    "django-ninja>=1.4.1",
    "pillow>=11.3.0",
    "pyjwt>=2.10.1",
]
