# Generated by Django 5.2 on 2025-05-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_barkmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='barkmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
