# Generated by Django 5.2 on 2025-05-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_authtokenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtokenmodel',
            name='token_type',
            field=models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token')], default='access', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='authtokenmodel',
            unique_together={('user', 'token_type')},
        ),
    ]
