# Generated by Django 5.2 on 2025-07-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_barkmodel_sniff_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogusermodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
